services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-net

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.16.6
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - es-net

  redis:
    container_name: redis-container
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - es-net

  postgres:
    container_name: postgres-container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_shop_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - es-net

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - es-net

  backend:
    container_name: shoppe-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - es-net

networks:
  es-net:
    driver: bridge

volumes:
  esdata: {}
  pgdata: {}